FROM mcr.microsoft.com/dotnet/sdk:9.0@sha256:fe3c1ed472bb0964c100f06aa9b1759f5ed84e0dfe6904d60f6a82159d3c7ae4 AS development
EXPOSE 8080
WORKDIR /Application

ENV ASPNETCORE_ENVIRONMENT=Development

RUN dotnet tool install --global dotnet-ef --version 9.0.4
ENV PATH="${PATH}:/root/.dotnet/tools"

CMD ["dotnet", "run", "--project", "./Application.csproj", "-c", "Debug", "-v", "normal"]