---
- name: Bootstrap deploy user as root
  hosts: vps
  remote_user: root
  roles:
    - role: setup-droplet
      vars:
        run_bootstrap: true

- name: Harden server as deploy
  hosts: vps
  remote_user: deploy
  become: true
  roles:
    - role: setup-droplet
      vars:
        run_bootstrap: false
