---
- block:
    - name: Create deploy user
      user:
        name: deploy
        shell: /bin/bash
        create_home: true

    - name: Ensure deploy’s .ssh dir exists
      file:
        path: /home/deploy/.ssh
        state: directory
        owner: deploy
        group: deploy
        mode: '0700'

    - name: Add SSH public key for deploy
      authorized_key:
        user: deploy
        key: "{{ lookup('file','deploy_key.pub') }}"
        state: present

    - name: Grant deploy user passwordless sudo
      copy:
        dest: /etc/sudoers.d/deploy
        content: "deploy ALL=(ALL) NOPASSWD:ALL"
        mode: '0440'
  when: run_bootstrap | bool

- block:
    - name: Disable SSH root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        backrefs: yes

    - name: Disable SSH password auth
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        backrefs: yes

    - name: Install UFW and Fail2Ban
      apt:
        name:
          - ufw
          - fail2ban
        state: present
        update_cache: yes

    - name: Allow SSH through UFW
      ufw:
        rule: allow
        name: OpenSSH

    - name: Allow HTTP/HTTPS through UFW
      ufw:
        rule: allow
        port: "{{ item }}"
        loop:
          - 80
          - 443
        proto: tcp

    - name: Enable UFW
      ufw:
        state: enabled
        logging: on

    - name: Ensure Fail2Ban is running and enabled
      service:
        name: fail2ban
        state: started
        enabled: yes

    - name: Restart SSH to apply changes
      service:
        name: ssh
        state: restarted
  when: not run_bootstrap | bool
