---
- name: Create deploy user
  user:
    name: deploy
    shell: /bin/bash
    state: present
    create_home: true

- name: Ensure deploy .ssh directory exists
  file:
    path: /home/deploy/.ssh
    state: directory
    owner: deploy
    group: deploy
    mode: '0700'

- name: Add SSH public key for deploy user
  authorized_key:
    user: deploy
    path: /home/deploy/.ssh/authorized_keys
    state: present
    key: "{{ lookup('file', 'deploy_key.pub') }}"

- name: Ensure correct perms on authorized_keys
  file:
    path: /home/deploy/.ssh/authorized_keys
    owner: deploy
    group: deploy
    mode: '0600'

- name: Grant deploy user passwordless sudo
  copy:
    dest: /etc/sudoers.d/deploy
    content: "deploy ALL=(ALL) NOPASSWD:ALL"
    mode: '0440'

- name: Install UFW
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Allow SSH through UFW
  ufw:
    rule: allow
    name: OpenSSH

- name: Allow HTTP/HTTPS through UFW
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 80
    - 443

- name: Enable UFW
  ufw:
    state: enabled
    logging: on
