---
- name: Create deploy user
  user:
    name: deploy
    shell: /bin/bash
    state: present
    create_home: true

- name: Add SSH key for deploy user
  authorized_key:
    user: deploy
    key: "{{ lookup('file', 'deploy_key.pub') }}"
    state: present

- name: Grant deploy user passwordless sudo
  copy:
    dest: /etc/sudoers.d/deploy
    content: "deploy ALL=(ALL) NOPASSWD:ALL"
    mode: '0440'

- name: Install UFW
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Allow SSH through UFW
  ufw:
    rule: allow
    name: OpenSSH

- name: Allow HTTP/HTTPS through UFW
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 80
    - 443

- name: Enable UFW
  ufw:
    state: enabled
    logging: on
