name: Provision Droplet

on:
  workflow_dispatch:
    inputs:
      droplet_name:
        description: "Name of the droplet"
        required: true
        default: "my-vps"
      size:
        description: "Droplet size (e.g. s-1vcpu-512mb-10gb)"
        required: true
        default: "s-1vcpu-512mb-10gb"
      image:
        description: "Image slug (e.g. ubuntu-22-04-x64)"
        required: false
        default: "ubuntu-22-04-x64"

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve \
          -var="do_token=${{ secrets.DO_TOKEN }}" \
          -var="ssh_key_fingerprint=${{ secrets.SSH_KEY_FINGERPRINT }}" \
          -var="droplet_name=${{ github.event.inputs.droplet_name }}" \
          -var="region=fra1" \
          -var="size=${{ github.event.inputs.size }}" \
          -var="image=${{ github.event.inputs.image }}"
      working-directory: terraform

    - name: Capture Droplet IP
      id: droplet_ip
      working-directory: terraform
      run: |
        # 1) get raw output without ANSI/color codes
        raw_ip=$(terraform output -raw droplet_ip -no-color)

        # 2) pull out the first IPv4-looking string
        ip=$(echo "$raw_ip" | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' | head -n1)

        # 3) set it as the step output
        echo "ip=$ip" >> $GITHUB_OUTPUT

    - name: Harden Droplet via SSH
      working-directory: terraform
      run: |
        # write out the private key
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
        chmod 600 id_rsa

        IP="${{ steps.droplet_ip.outputs.ip }}"
        echo "Using Droplet IP: $IP"
        if [ -z "$IP" ]; then
          echo "ERROR: IP is empty" >&2
          exit 1
        fi

        # wait for SSH port 22 to be open & accepting keys
        echo "Waiting for SSH to become available on $IP..."
        until ssh -o BatchMode=yes -o ConnectTimeout=5 -i id_rsa root@"$IP" 'echo ✓' &>/dev/null; do
          echo "  still waiting…"
          sleep 5
        done

        # finally, run the hardening script
        ssh -o StrictHostKeyChecking=no -i id_rsa root@"$IP" 'bash -s' < ../scripts/harden.sh
