name: Setup Droplet

on:
  workflow_dispatch:
    inputs:
      droplet_name:
        description: "Name"
        required: true
      droplet_size:
        description: "Size"
        required: true
        default: "s-1vcpu-512mb-10gb"
      droplet_image:
        description: "Image"
        required: true
        default: "ubuntu-24-04-x64"
      droplet_region:
        description: "Region"
        required: true
        default: "fra1"

jobs:
  setup_droplet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"
          terraform_wrapper: false 

      - name: Terraform init
        run: terraform init -no-color
        working-directory: infra/terraform

      - name: Terraform apply
        run: |
          terraform apply -auto-approve \
            -var="do_token=${{ secrets.DO_TOKEN }}" \
            -var="ssh_key_fingerprint=${{ secrets.SSH_KEY_FINGERPRINT }}" \
            -var="droplet_name=${{ github.event.inputs.droplet_name }}" \
            -var="size=${{ github.event.inputs.droplet_size }}" \
            -var="image=${{ github.event.inputs.droplet_image }}" \
            -var="region=${{ github.event.inputs.droplet_region }}"
        working-directory: infra/terraform

      - name: Capture droplet IP
        id: droplet_ip
        working-directory: infra/terraform
        run: |
          raw_ip=$(terraform output -raw droplet_ip -no-color)
          ip=$(echo "$raw_ip" | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' | head -n1)
          echo "ip=$ip" >> $GITHUB_OUTPUT

      - name: Set up Python & install Ansible
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core

      - name: Verify Ansible
        run: |
          ansible --version
          ls -R infra/ansible

      - name: Prepare SSH key for Ansible
        run: |
          mkdir -p infra/ansible
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > infra/ansible/ansible_key
          chmod 600 infra/ansible/ansible_key

      - name: Generate Ansible inventory
        run: |
          cat > infra/ansible/inventory.ini <<EOF
          [vps]
          ${{ steps.droplet_ip.outputs.ip }} ansible_user=root ansible_ssh_private_key_file=ansible_key
          EOF
      
      - name: Verify connectivity to VPS
        working-directory: infra/ansible
        run: ansible all -m ping --inventory inventory.ini
